{
  "fid": 20099,
  "title": "相手が「<<4818>>」を発動しているターンに、自分は「<<12798>>」を発動できますか？",
  "question": "自分のターンに相手が「<<4818>>」を発動し、『①：自分フィールドに「羊トークン」（獣族・地・星１・攻／守０）４体を守備表示で特殊召喚する。このトークンはアドバンス召喚のためにはリリースできない』効果処理を適用しているターンです。\n\nこの状況で、自分は「<<12798>>」の『①：自分フィールドに「超量士」モンスターが３種類以上存在する場合に発動できる。相手フィールドのカードを全て持ち主のデッキに戻す。その後、相手はエクストラデッキからモンスター１体を召喚条件を無視して特殊召喚する』効果を発動する事はできますか？",
  "answer": "質問の状況の場合、相手はこのターンに「<<4818>>」発動しており、『このカードを発動するターン、自分はこのカードの効果以外ではモンスターを召喚・反転召喚・特殊召喚できない』状態となっています。\n\n「<<12798>>」はその効果処理によって、『その後、相手はエクストラデッキからモンスター１体を召喚条件を無視して特殊召喚する』処理を行いますので、相手が特殊召喚を行えないターンに、自分は「<<12798>>」を発動する事はできません。",
  "date": "2017-03-24"
}
